export const ROUTS = {
    HOME: '/',
    JOBS: '/jobs',
    NDA: '/nda',
    CASES: '/cases',
    CASE: '/case/:category',
    ABOUT: '/about',
    //DEVELOP: '/development',
    POLICY: '/privacy',
    SERVICES: '/services/:service',
    BONUSES: '/bonuses',
    CONTACTS: '/contacts',
    CASE_GRANIT: '/case/granit-company',
    CASE_SWISS: '/case/swiss',
    CASE_PARTY_INTEL: '/case/party-intel',
    CASE_PAPPY_ELEPHANT: '/case/happy-elephant',
    CASE_OPTICS: '/case/optics',
}